version: '3.3'

services:
  web:
    container_name: chatGpt-api
    build:
      context: .
    environment:
      - development
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet

volumes:
  database-data:
networks:
  webnet:
